name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    # ✅ This ensures CI also runs on Dependabot PRs
    if: github.actor == 'dependabot[bot]' || github.event_name != 'pull_request'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint || echo "Linting failed!"

      - name: Run tests
        run: npm test || echo "Tests failed!"
