name: 🕒 Scheduled Tasks - Update Satellite Data

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:  # lets you run manually from the Actions tab

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run daily satellite data update
        run: node run.js

      - name: Upload log output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: satellite-update-log
          path: ./public/data/
